### ISSUE TITLE
Feld rückt auf z.b. 1.3.2 in spalte 2

### ISSUE THREAD

**Issue by Abcde110o** [Teck-Digital/pbl#16]

**Comment by HeinzSama** [comment]
Kannst du ein screenshot schicken? Ich kriegs nicht reproduziert

**Comment by Abcde110o** [comment]
![regalfhler](https://user-images.githubusercontent.com/48602991/71786701-b904db00-300e-11ea-88c6-b05ad5490273.PNG)

**Comment by HeinzSama** [comment]
Ah, ich weiß worans liegt.
Mach ich gleich

**Comment by Abcde110o** [comment]
👍🏻
